### PR TITLE
Contao 5 support

### PR DESCRIPTION
**Pull request by Tastaturberuf**
Es bleibt ein Bug den wo ich den Ursprung nicht finde, über die eigene Route wird oben immer der Cache-Status ausgegeben. 

Das ist aber über dem eigentlichen Template. 

image
image

### CODE REVIEW

**Comment by Tastaturberuf** [comment]
Das ganze habe ich in Contao 5.1 und 4.13 getestet.

**Comment by zoglo** [comment]
@Tastaturberuf 

I did test your branch on Contao 4.13 and 5.1. However, I could not reproduce the issue you've mentioned above:
```
Es bleibt ein Bug den wo ich den Ursprung nicht finde, über die eigene Route wird oben immer der Cache-Status ausgegeben.

Das ist aber über dem eigentlichen Template.
```

Is there any way to reproduce it?

**Comment by Tastaturberuf** [comment]
Its only in the custom route domain.tld/contao/style-manager-import. i have used a fresh 5.1 with some other extentions for the project and a 4.13 from another project. in both installation i have this error. 

```
 "require": {
        "contao/calendar-bundle": "^5.1",
        "contao/comments-bundle": "^5.1",
        "contao/conflicts": "@dev",
        "contao/faq-bundle": "^5.1",
        "contao/listing-bundle": "^5.1",
        "contao/manager-bundle": "5.1.*",
        "contao/news-bundle": "^5.1",
        "contao/newsletter-bundle": "^5.1",
        "oveleon/contao-component-style-manager": "@dev",
        "madeyourday/contao-rocksolid-custom-elements": "^2.4",
        "fritzmg/contao-swiper": "^4.3"
    }
```

**Comment by fritzmg** [comment]
The extension does not really work in Contao 5 due to

```
Symfony\Component\ErrorHandler\Error\ClassNotFoundError:
Attempted to load class "Table" from the global namespace.
Did you forget a "use" statement for e.g. "Symfony\Component\Console\Helper\Table", "Spatie\SchemaOrg\Table", "League\CommonMark\Extension\Table\Table", "Doctrine\ORM\Mapping\Table" or "Doctrine\DBAL\Schema\Table"?
```

(see https://github.com/oveleon/contao-component-style-manager/pull/82) and other issues, e.g.

```
TypeError:
Oveleon\ContaoComponentStyleManager\EventListener\DataContainer\StyleManagerArchiveListener::importConfigButton(): Argument #1 ($href) must be of type string, null given, called in vendor\contao\core-bundle\contao\classes\DataContainer.php on line 1072

  at vendor\oveleon\contao-component-style-manager\src\EventListener\DataContainer\StyleManagerArchiveListener.php:46
  at Oveleon\ContaoComponentStyleManager\EventListener\DataContainer\StyleManagerArchiveListener->importConfigButton(null, 'Import', 'Import a config', 'header_style_manager_import header_icon', ' style="background-image:url(\'/system/themes/flexible/icons/theme_import.svg\')"', 'tl_style_manager_archive', array())
     (vendor\contao\core-bundle\contao\classes\DataContainer.php:1072)
```

I could not reproduce the error with the above dependencies in Contao 4.13.

**Comment by zoglo** [comment]
@fritzmg, did you check *this* Pull-Request or the current main-branch?

**Comment by fritzmg** [comment]
Ah, no, only @dev

**Comment by fritzmg** [comment]
I can reproduce the issue in this PR. The cause is that you are using

```php
return new Response($this->render(…))
```

But `$this->render` already returns a `Response`. So it should just be `return $this->render(…)`.

**Comment by zoglo** [comment]
@Tastaturberuf 
@fritzmg 

Could you test the last changes again?

**Comment by fritzmg** [comment]
lgtm 👍

**Review by zoglo — APPROVED** [review]

**Comment by zoglo** [comment]
Thank you @Tastaturberuf and @fritzmg

**Comment by Tastaturberuf** [comment]
I will try it tomorrow on my production setup. at the weekend i will take a look for the twig integration.

**Pull request merged**
